dateModified: 1662913724
email:
  fromEmail: craftcms@example.com
  fromName: 'My example site'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    5ff82d17-b3a4-40ee-96a7-8494e769befd: Common # Common
    49ad2a43-9494-434e-b669-282d4fc86ac0: 'My example site' # My example site
    018749f1-db25-4588-8bac-6199e443af2f: 'My example site' # My example site
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'My example site'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
